Repository woocommerce/woocommerce-beta-tester, pull requests merged in 2019-03, with the labels that each got.

#50 Fix exception when running against master/3.6-dev
  includes/class-wc-beta-tester-admin-menus.php
Labels: status: approved

#51 Check WC version before calling WC_API::rest_api_includes()
  includes/class-wc-beta-tester-admin-menus.php
Labels: status: approved

#52 Add Travis configuration file to the repository
  .travis.yml
  assets/js/version-information.js
  assets/js/version-picker.js
  includes/class-wc-beta-tester-admin-assets.php
  includes/class-wc-beta-tester-admin-menus.php
  includes/class-wc-beta-tester-plugin-upgrader.php
  includes/class-wc-beta-tester-settings.php
  includes/class-wc-beta-tester-version-picker.php
Labels: status: approved, status: needs review

#55 Fixed multiple modals after click in "Release x.x.x information"
  assets/js/version-information.js
  assets/js/version-information.min.js
  assets/js/version-picker.min.js
  package-lock.json
Labels: status: needs review
